pipeline {
  agent none
  stages {
    stage('Checkout') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        checkout scm
      }
    }
    stage('Install Dependencies') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'npx yarn install'     // Use npx to run yarn install
      }
    }
    stage('Build') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'       // Optional: Check Node.js version
        sh 'npx yarn --version'   // Optional: Check Yarn version
        sh 'npx yarn build'       // Use npx to run yarn build
      }
    }
  }
}
